### ISSUE TITLE
 feat: Conditional automount at execution

### ISSUE THREAD

**Issue by k-kinzal** [k-kinzal/aliases#17]
I had a problem.

```
/usr/local/bin/kubectl:
  image: chatwork/kubectl
  tag: 1.11.2
  env:
    KUBECONFIG: $KUBECONFIG
  volume:
  - $HOME/.kube:/root/.kube
  - $PWD:/kube
  workdir: /kube
```

```
$ KUBECONFIG=$HOME/Downloads/kube-config.cfg kubectl config view --flatten
```

it does not work because it is not mounted `$HOME/Downloads/kube-config.cfg`.

it possible to solve this problem if it can be automatically mounted under conditions at execution.
