### ISSUE TITLE
Execution of the command does not end.

### ISSUE THREAD

**Issue by k-kinzal** [k-kinzal/aliases#21]
**aliases.yaml**
```
/usr/local/bin/kubectl:
  image: chatwork/kubectl
  tag: 1.11.2
  volume:
  - $HOME/.kube:/root/.kube
  - $PWD:/kube
  workdir: /kube

/usr/local/bin/alpine:
  image: alpine
  tag: 3.8
  dependencies:
  - /usr/local/bin/kubectl
```

```
$ kubectl version -c
```

It works when `kubectl` is executed

```
$ alpine kubect version -c
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

```

But execute `alpine` through `kubect` does not end the command.
In order to solve this problem `alpine` needs to be `tty: true`.
