### ISSUE TITLE
Error occurs when `tty` is enabled

### ISSUE THREAD

**Issue by k-kinzal** [k-kinzal/aliases#22]
Enabling tty occurs error in some cases.

## Case1

**alises.yaml**
```
/usr/local/bin/alpine:
  image: alpine
  tag: 3.8
  tty: true
```

```
$ echo "foo" | alpine sh -c "cat -"
the input device is not a TTY
```

## Case 2

**aliases.yaml**
```
/usr/local/bin/helm:
  image: chatwork/helm
  tag: 2.11.0
  volume:
  - /tmp:/tmp
  - $HOME/.kube:/root/.kube
  - $HOME/.helm:/root/.helm
  - $PWD:/helm
  - $PWD:/helmfile
  workdir: /helm

/usr/local/bin/helmfile:
  image: chatwork/helmfile
  tag: 0.40.1-2.10.0-1.11.3
  volume:
  - /tmp:/tmp
  - $HOME/.helm:/root/.helm
  - $PWD:/helmfile
  workdir: /helmfile
  dependencies:
  - /usr/local/bin/helm
```

We need a `tty` when using `helm secret edit` with helm.
However, to execute helm from helmfile we need to turn off `tty`.
