### ISSUE TITLE
feat: Automatic download of docker binary

### ISSUE THREAD

**Issue by k-kinzal** [k-kinzal/aliases#32]
An error occurs when sharing docker container and docker binary on Ubuntu.

https://twitter.com/amaya382/status/1077874567119396864
https://amaya382.hatenablog.jp/entry/2016/10/05/030254

It is necessary to solve this problem in order to operate on CircleCI as a use case.

## proposal

```yaml
/bin/sh:
  docker:
    image: docker
    tag: 18.09.0
  image: alpine
  tag 3.8
  command: /bin/sh
  privileged: true
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
```

```
if [ ! -f $ALIASES_HOME/docker/docker-18.09.0 ]; then
  docker run -v $ALIASES_HOME/docker:/data --name docker-18-09-0 docker:18.09.0 /bin/sh -c 'cp $(which docker) /data/docker-18.09.0'
fi
docker run --interactive --privileged --rm --volume $ALIASES_HOME/docker/docker-18.09.0:/usr/local/bin/docker --volume /var/run/docker.sock:/var/run/docker.sock alpine:${SH_VERSION:-"3.8"} /bin/sh "$@"
```

We propose to download docker binary via docker image.

It is preferable that the downloading timing be executed when `aliases` is running.
