### ISSUE TITLE
feat:  Inherit dependent parameters

### ISSUE THREAD

**Issue by k-kinzal** [k-kinzal/aliases#37]
There is a problem that YAML becomes long when using [helm secrets](https://github.com/futuresimple/helm-secrets).

```yaml
/bin/sops:
  image: mozilla/sops
  tag: 8fcd61e8a3d1709ae37d7ae55d49cfe6b8aeda8b
  entrypoint: /bin/sops
  env:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_PROFILE: $AWS_PROFILE
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    SOPS_KMS_ARN: $SOPS_KMS_ARN
  volume:
  - $HOME/.aws:/root/.aws
  - $PWD:/sops
  workdir: /sops

/bin/bash:
  image: bash
  tag: 4.4.23
  env:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_PROFILE: $AWS_PROFILE
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    SOPS_KMS_ARN: $SOPS_KMS_ARN
  workdir: /bash
  dependencies:
  - /bin/sops

/usr/local/bin/helm:
  image: chatwork/helm
  tag: 2.11.0
  env:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_PROFILE: $AWS_PROFILE
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    SOPS_KMS_ARN: $SOPS_KMS_ARN
  volume:
  - $HOME/.kube:/root/.kube
  - $HOME/.helm:/root/.helm
  - $PWD:/helm
  workdir: /helm
  dependencies:
  - /bin/bash
```

In this way we need to inherit the environment variable.
This not very readable.

## proposal

```
/bin/sops:
  image: mozilla/sops
  tag: 8fcd61e8a3d1709ae37d7ae55d49cfe6b8aeda8b
  entrypoint: /bin/sops
  env:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_PROFILE: $AWS_PROFILE
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    SOPS_KMS_ARN: $SOPS_KMS_ARN
  volume:
  - $HOME/.aws:/root/.aws
  - $PWD:/sops
  workdir: /sops

/bin/bash:
  image: bash
  tag: 4.4.23
  workdir: /bash
  dependencies:
  - /bin/sops

/usr/local/bin/helm:
  image: chatwork/helm
  tag: 2.11.0
  volume:
  - $HOME/.kube:/root/.kube
  - $HOME/.helm:/root/.helm
  - $PWD:/helm
  workdir: /helm
  dependencies:
  - /bin/bash
```

```bash
$ SOPS_KMS_ARN=xxx AWS_PROFILE=[your procile] helm secrets enc secrets.yaml
```

I would like to readability by inheriting the dependency parameters.
