### ISSUE TITLE
feat: Automatic argument mounting

### ISSUE THREAD

**Issue by k-kinzal** [k-kinzal/aliases#43]
Derived from https://github.com/k-kinzal/aliases/issues/17.

## Proposal

```yaml
/bin/curl:
  image: tutum/curl
  tag: alpine
  experimental: true
  entrypoint: curl
```

```
$ curl ... -O $HOME/Downloads
$ cat $HOME/Downloads/[your download file]
```

We propose mounting the path specified by the argument.

* `host`: Always mount if the argument contains a path
* `guest`: If mounted on `guest` mount it. Otherwise, a warning is displayed.

However, this is complicated.
Therefore we want to work only when `experimental` flag is enabled.
If it stabilizes, remove the flag of `experimental` to make it the default behavior.
