### ISSUE TITLE
feat:  Automatic mounting of environment variables

### ISSUE THREAD

**Issue by k-kinzal** [k-kinzal/aliases#44]
Derived from #17.

## Proposal

```yaml
/usr/local/bin/kubectl:
  image: chatwork/kubectl
  tag: 1.11.2
  experimental: true
  env:
    KUBECONFIG: $KUBECONFIG
  volume:
  - $HOME/.kube:/root/.kube
  - $PWD:/kube
  workdir: /kube
```

```
$ KUBECONFIG=$HOME/.kube2/config:$HOME/.kube/config kubectl get all
```

We propose to mount the path automatically if the environment variable specified in `env` is in PATH format (colon delimited).

However, this is complicated.
Therefore we want to work only when `experimental` flag is enabled.
If it stabilizes, remove the flag of `experimental` to make it the default behavior.
