### ISSUE TITLE
feat:  If there is a symbolic link in the mounted directory, a warning is displayed.

### ISSUE THREAD

**Issue by k-kinzal** [k-kinzal/aliases#45]
Derived from https://github.com/k-kinzal/aliases/issues/17.

## Proposal

```
/usr/local/bin/helm:
  image: chatwork/helm
  tag: 2.11.0
  volume:
  - $HOME/.kube:/root/.kube
  - $HOME/.helm:/root/.helm
  - $PWD:/helm
  workdir: /helm
```

```
$ aliases gen
WARNGING: /Users/k-kinzal/.helm/plugins/helm-secrets -> /root/.helm/cache/plugins/https-github.com-futuresimple-helm-secrets: not mounting this symbolic link destination
```

We propose to display warnings for symbolic links.
If a symbolic link exists and the link destination is not mounted, a warning is displayed.
