### ISSUE TITLE
feat: Supports extend of entrypoint

### ISSUE THREAD

**Issue by k-kinzal** [k-kinzal/aliases#49]
We may need `helm plugins` when using `helm`.
It is very troublesome to recreate containers.

So we need a way to install A with `entrypoint`.

## proposal

**aliases.yaml**
```
/usr/local/bin/helm
  image: chatwork/helm
  tag: 2.11.0
  volumes:
  - $HOME/.kube:/root/.kube
  - $HOME/.helm:/root/.helm
  - $PWD:/helm
  workdir: /helm
  entrypoint: |
    #!/bin/sh
    if [ -f $(helm home)/plugins/helm-import ]; then
      helm plugin install https://github.com/k-kinzal/helm-import
    if
    helm "$@"
  dependencies:
  - /bin/bash
  - /bin/git
```

**script**
```
$ docker run ... -v $HOME/.aliases/entrypoints/xxx:/xxx --entrypoint /xxx chatwork/helm:${HELM_VERSION:-2.11.0}
```

We think that we should be able to extend `entrypoint` like this.
