### ISSUE TITLE
feat: Remove empty environment variable

### ISSUE THREAD

**Issue by k-kinzal** [k-kinzal/aliases#50]
`awscli` does not work if there is an empty environment variable.

```yaml
  env:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY:
    AWS_PROFILE: $AWS_PROFILE
    AWS_DEFAULT_REGION: $AWS_REGION
```

Therefore, empty environment variables should be removed.

However, we must consider cases where you want to use empty environment variables.
For example, when enclosed in double quotes, it is necessary to propose a workaround such as using an empty environment variable.
