### ISSUE TITLE
Detect problems when typo with YAML.

### ISSUE THREAD

**Issue by k-kinzal** [k-kinzal/aliases#9]
I typo.

```
/usr/local/bin/jq:
  image: chatwork/jq
  tag: 1.5-r5
  volumes:
  - $PWD:/jq
  workdir: /jq
```

`volume` rather than `volumes` is correct.
We do not want to use time for this, so I want to make an undefined key an error.
